kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-bestem-pensjonsopptjening
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: OMSORGSARBEID_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: OMSORGSOPPTJENING_BESTEM_GROUP_ID
      value: omsorgsopptjening-bestem-group
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api
    - name: BESTEMSAK_URL
      value: https://pensjon-pen-q2.nais.preprod.local/pen/api/bestemsak/v1
    - name: OPPGAVE_URL
      value: https://oppgave.dev-fss-pub.nais.io/api/v1/oppgaver
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        cascadingDelete: true
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorgsopptjening
        tier: db-custom-4-15360
        databases:
          - name: omsorgsopptjening
            envVarPrefix: DATABASE
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "10"
      memory: "4096Mi"
    requests:
      cpu: "1"
      memory: "2048Mi"