kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-bestem-pensjonsopptjening
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: OMSORGSOPPTJENING_BESTEM_GROUP_ID
      value: omsorgsopptjening-bestem-group
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorgsopptjeningdb
        tier: db-custom-4-15360
        databases:
          - name: omsorgsopptjeningdb
            envVarPrefix: DATABASE
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  image: {{ image }}
  ingresses:
    - https://omsorgsopptjening-bestem-pensjonsopptjening.dev.intern.nav.no
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 40
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 40
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 1024Mi