kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-bestem-pensjonsopptjening
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api
    - name: PEN_BASE_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io/pen
    - name: PEN_API_ID
      value: dev-fss.pensjon-q2.pensjon-pen-q2
    - name: OPPGAVE_URL
      value: https://oppgave.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_API_ID
      value: dev-fss.oppgavehandtering.oppgave
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
    - name: MEDLEMSKAP_URL
      value: http://medlemskap-medl-api.team-rocket
    - name: MEDLEMSKAP_API_ID
      value: dev-gcp.team-rocket.medlemskap-medl-api
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: OMSORGSOPPTJENING_CONSUMER_GROUP
      value: omsorgsopptjening-bestem-pensjonsopptjening
    - name: GYLDIG_OPPTJENINGSAR
      value: "2024"
  envFrom:
    - secret: unleash-api-token
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        cascadingDelete: false
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorgsopptjening-bestem-pensjonsopptjening-db
        tier: db-f1-micro
        databases:
          - name: omsorgsopptjening-bestem-pensjonsopptjening-db
            envVarPrefix: DATABASE
        flags:
          - name: cloudsql.enable_pgaudit
            value: "on"
          - name: pgaudit.log
            value: 'write'
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "7ef907b4-ec9f-47dd-ab41-4e54ba32ceb1" #AAD pensjonopptjening testgruppe

  ingresses:
    - https://omsorgsopptjening-bestem-pensjonsopptjening.intern.dev.nav.no
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: oppgave.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pensjonopptjening-unleash-api.nav.cloud.nais.io
      rules:
        - application: logging
          namespace: nais-system
        - application: medlemskap-medl-api
          namespace: team-rocket
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 120
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 120
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  replicas:
    # TODO: Antall replikas er satt til 0 for å hindre ressursbruk mens applikasjonen er idle
    # TODO: Applikasjonen feiler pga en rar konflikt i spring-konfigurasjonen. Må fikses før applikasjonen kan kjøre.
    min: 1
    max: 1
  resources:
    limits:
      cpu: "2"
      memory: 4096Mi
    requests:
      cpu: 500m
      memory: 1024Mi
