kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-bestem-pensjonsopptjening-q1
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: PDL_URL
      value: https://pdl-api-q1.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api-q1
    - name: PEN_BASE_URL
      value: deaktivert
    - name: PEN_API_ID
      value: deaktivert
    - name: OPPGAVE_URL
      value: deaktivert
    - name: OPPGAVE_API_ID
      value: deaktivert
    - name: POPP_URL
      value: https://pensjon-popp.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q1
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening-q1
    - name: OMSORGSOPPTJENING_CONSUMER_GROUP
      value: omsorgsopptjening-bestem-pensjonsopptjening-q1
    - name: GYLDIG_OPPTJENINGSAR
      value: "2021"
  envFrom:
    - secret: unleash-api-token
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        cascadingDelete: true
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorgsopptjening-bestem-pensjonsopptjening-db-q1
        tier: db-custom-4-15360
        databases:
          - name: omsorgsopptjening-bestem-pensjonsopptjening-db-q1
            envVarPrefix: DATABASE
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pdl-api-q1.dev-fss-pub.nais.io
        - host: pensjon-popp.dev-fss-pub.nais.io
        - host: pensjonopptjening-unleash-api.nav.cloud.nais.io
  image: { { image } }
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 4
    max: 4
  resources:
    limits:
      cpu: "10"
      memory: "4096Mi"
    requests:
      cpu: "1"
      memory: "2048Mi"
