kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-bestem-pensjonsopptjening
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: dev-fss.pdl.pdl-api
    - name: PEN_BASE_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io/pen
    - name: PEN_API_ID
      value: dev-fss.pensjon-q2.pensjon-pen-q2
    - name: OPPGAVE_URL
      value: https://oppgave.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_API_ID
      value: dev-fss.oppgavehandtering.oppgave
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: dev-fss.pensjonopptjening.pensjon-popp-q2
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: OMSORGSOPPTJENING_CONSUMER_GROUP
      value: omsorgsopptjening-bestem-pensjonsopptjening
    - name: GYLDIG_OPPTJENINGSAR
      value: "2022"
  envFrom:
    - secret: unleash-api-token
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        cascadingDelete: true
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorgsopptjening-bestem-pensjonsopptjening-db
        tier: db-custom-4-15360
        databases:
          - name: omsorgsopptjening-bestem-pensjonsopptjening-db
            envVarPrefix: DATABASE
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: oppgave.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pensjonopptjening-unleash-api.nav.cloud.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 2
      memory: "4096Mi"
    requests:
      cpu: 100m
      memory: "2048Mi"
