kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: omsorgsopptjening-bestem-pensjonsopptjening
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_API_ID
      value: prod-fss.pdl.pdl-api
    - name: PEN_BASE_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io/pen
    - name: PEN_API_ID
      value: prod-fss.pensjondeployer.pensjon-pen
    - name: OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_API_ID
      value: prod-fss.oppgavehandtering.oppgave
    - name: POPP_URL
      value: https://pensjon-popp.prod-fss-pub.nais.io/popp/api
    - name: POPP_API_ID
      value: prod-fss.pensjonopptjening.pensjon-popp
    - name: MEDLEMSKAP_URL
      value: https://medlemskap-medl-api.prod-fss-pub.nais.io
    - name: MEDLEMSKAP_API_ID
      value: prod-fss.team-rocket.medlemskap-medl-api
    - name: OMSORGSOPPTJENING_TOPIC
      value: pensjonopptjening.omsorgsopptjening
    - name: OMSORGSOPPTJENING_CONSUMER_GROUP
      value: omsorgsopptjening-bestem-pensjonsopptjening
    - name: GYLDIG_OPPTJENINGSAR
      value: "2023"
  envFrom:
    - secret: unleash-api-token
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        cascadingDelete: false
        diskAutoresize: true
        pointInTimeRecovery: true
        name: omsorgsopptjening-bestem-pensjonsopptjening-db
        tier: db-custom-4-15360
        databases:
          - name: omsorgsopptjening-bestem-pensjonsopptjening-db
            envVarPrefix: DATABASE
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "abd710c7-b01d-48e6-98b9-83ff615edf26" #AAD nais-team-pensjonopptjening
  secureLogs:
    enabled: true
  ingresses:
    - https://omsorgsopptjening-bestem-pensjonsopptjening.intern.nav.no
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: pensjon-pen.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
        - host: pensjon-popp.prod-fss-pub.nais.io
        - host: pensjonopptjening-unleash-api.nav.cloud.nais.io
        - host: medlemskap-medl-api.dev-fss-pub.nais.io
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 120
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 120
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    # TODO: Antall replikas er satt til 0 for å hindre ressursbruk mens applikasjonen er idle
    min: 0
    max: 0
  resources:
    limits:
      cpu: "1000m"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"