DROP TABLE OMSORGSARBEIDSMOTTAKER;
DROP SEQUENCE omsorgsarbeidsmottaker_seq;

CREATE SEQUENCE omsorgsarbeidsmottaker_seq INCREMENT 50;
CREATE TABLE OMSORGSARBEIDSMOTTAKER
(
    OMSORGSARBEID_PERIODE_ID  BIGINT             not null,
    PERSON_ID                 BIGINT             not null,
    PRIMARY KEY(OMSORGSARBEID_PERIODE_ID, PERSON_ID),
    CONSTRAINT fk_periode_omsorgsarbeidsmottaker FOREIGN KEY (OMSORGSARBEID_PERIODE_ID) REFERENCES OMSORGSARBEID_PERIODE (OMSORGSARBEID_PERIODE_ID),
    CONSTRAINT fk_person_omsorgsarbeidsmottaker FOREIGN KEY (PERSON_ID) REFERENCES PERSON (PERSON_ID)
);